"""add_local_account_auth

Revision ID: 265af883ccf6
Revises: a27f4314795e
Create Date: 2026-09-05 15:18:34.609456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '265af883ccf6'
down_revision: Union[str, Sequence[str], None] = 'a27f4314795e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('first_name', sa.String(length=120), server_default='', nullable=False))
    op.add_column('app_user', sa.Column('surname', sa.String(length=120), server_default='', nullable=False))
    op.add_column('app_user', sa.Column('password_hash', sa.Text(), server_default='', nullable=False))
    op.add_column('app_user', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('role_code_verified_for', sa.Enum('SUPER_ADMIN', 'MUNICIPAL_ADMIN', 'OPERATOR', 'DRIVER', 'ANALYST', 'VIEWER', name='user_role', native_enum=False), nullable=True))
    op.add_column('app_user', sa.Column('role_code_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('privacy_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('session_token_hash', sa.String(length=128), nullable=True))
    op.add_column('app_user', sa.Column('session_issued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('failed_login_count', sa.Integer(), nullable=False))
    op.add_column('app_user', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('app_user', 'email',
               existing_type=sa.VARCHAR(length=320),
               server_default='',
               nullable=False)
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_role'), table_name='app_user')
    op.drop_constraint(op.f('uq_app_user_provider_sub'), 'app_user', type_='unique')
    op.create_index('ix_app_user_role_active', 'app_user', ['role', 'is_active'], unique=False)
    op.create_index('ix_app_user_session_expires', 'app_user', ['session_expires_at'], unique=False)
    op.create_index('ix_app_user_session_token_hash', 'app_user', ['session_token_hash'], unique=False)
    op.create_unique_constraint('uq_app_user_email', 'app_user', ['email'])
    op.create_check_constraint('ck_app_user_email_present', 'app_user', 'length(email) > 0')
    op.create_check_constraint('ck_app_user_failed_login_count', 'app_user', 'failed_login_count >= 0')
    op.create_check_constraint('ck_app_user_first_name_present', 'app_user', 'length(first_name) > 0')
    op.create_check_constraint('ck_app_user_password_hash', 'app_user', 'length(password_hash) > 0')
    op.create_check_constraint('ck_app_user_surname_present', 'app_user', 'length(surname) > 0')
    op.drop_column('app_user', 'subject')
    op.drop_column('app_user', 'role_source_group')
    op.drop_column('app_user', 'provider_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('provider_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('app_user', sa.Column('role_source_group', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('app_user', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('ck_app_user_surname_present', 'app_user', type_='check')
    op.drop_constraint('ck_app_user_password_hash', 'app_user', type_='check')
    op.drop_constraint('ck_app_user_first_name_present', 'app_user', type_='check')
    op.drop_constraint('ck_app_user_failed_login_count', 'app_user', type_='check')
    op.drop_constraint('ck_app_user_email_present', 'app_user', type_='check')
    op.drop_constraint('uq_app_user_email', 'app_user', type_='unique')
    op.drop_index('ix_app_user_session_token_hash', table_name='app_user')
    op.drop_index('ix_app_user_session_expires', table_name='app_user')
    op.drop_index('ix_app_user_role_active', table_name='app_user')
    op.create_unique_constraint(op.f('uq_app_user_provider_sub'), 'app_user', ['provider_name', 'subject'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_app_user_role'), 'app_user', ['role'], unique=False)
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.alter_column('app_user', 'email',
               existing_type=sa.VARCHAR(length=320),
               server_default=None,
               nullable=True)
    op.drop_column('app_user', 'last_failed_login_at')
    op.drop_column('app_user', 'locked_until')
    op.drop_column('app_user', 'failed_login_count')
    op.drop_column('app_user', 'session_expires_at')
    op.drop_column('app_user', 'session_issued_at')
    op.drop_column('app_user', 'session_token_hash')
    op.drop_column('app_user', 'privacy_accepted_at')
    op.drop_column('app_user', 'terms_accepted_at')
    op.drop_column('app_user', 'role_code_verified_at')
    op.drop_column('app_user', 'role_code_verified_for')
    op.drop_column('app_user', 'password_changed_at')
    op.drop_column('app_user', 'password_hash')
    op.drop_column('app_user', 'surname')
    op.drop_column('app_user', 'first_name')
    # ### end Alembic commands ###
