"""facility_operations_tracking

Revision ID: 3c5a9628e17c
Revises: 265af883ccf6
Create Date: 2026-09-05 16:23:10.562371
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c5a9628e17c'
down_revision: Union[str, Sequence[str], None] = '265af883ccf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('telemetry_status', sa.Enum('UNKNOWN', 'MOVING', 'IDLE', 'OFFLINE', 'STALE', name='telemetry_status', native_enum=False), nullable=False),
    sa.Column('telemetry_source', sa.Enum('NONE', 'SIMULATED', 'BROWSER_GPS', 'TRACKER_API', 'MANUAL', name='telemetry_source', native_enum=False), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tracker_device_id', sa.String(length=128), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accuracy_meters IS NULL OR accuracy_meters >= 0', name='ck_vehicle_location_accuracy_nonneg'),
    sa.CheckConstraint('heading_degrees IS NULL OR (heading_degrees >= 0 AND heading_degrees <= 360)', name='ck_vehicle_location_heading_range'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_vehicle_location_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_vehicle_location_longitude_range'),
    sa.CheckConstraint('speed_kmh IS NULL OR speed_kmh >= 0', name='ck_vehicle_location_speed_nonneg'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_location_muni_time', 'vehicle_location', ['municipality_id', 'recorded_at'], unique=False)
    op.create_index('ix_vehicle_location_time', 'vehicle_location', ['recorded_at'], unique=False)
    op.create_index('ix_vehicle_location_vehicle_time', 'vehicle_location', ['vehicle_id', 'recorded_at'], unique=False)
    op.add_column('app_user', sa.Column('assigned_entity_id', sa.Integer(), nullable=True))
    op.add_column('app_user', sa.Column('assigned_entity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_app_user_muni_assigned_entity', 'app_user', ['default_municipality_id', 'assigned_entity_id'], unique=False)
    op.create_foreign_key(None, 'app_user', 'entity', ['assigned_entity_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_bin_capacity_liters_nonneg', 'bin', 'capacity_liters >= 0')
    op.create_check_constraint('ck_bin_latitude_range', 'bin', 'latitude IS NULL OR (latitude >= -90 AND latitude <= 90)')
    op.create_check_constraint('ck_bin_longitude_range', 'bin', 'longitude IS NULL OR (longitude >= -180 AND longitude <= 180)')
    op.add_column('entity', sa.Column('subtype', sa.Enum('PRIMARY_SCHOOL', 'SECONDARY_SCHOOL', 'UNIVERSITY', 'COLLEGE', 'CLINIC', 'HOSPITAL_FACILITY', 'BUSINESS_PREMISES', 'HOUSEHOLD_UNIT', 'PUBLIC_SPACE_SITE', 'OTHER', name='entity_subtype', native_enum=False), nullable=True))
    op.add_column('entity', sa.Column('google_place_id', sa.String(length=255), nullable=True))
    op.add_column('entity', sa.Column('google_place_name', sa.String(length=255), nullable=True))
    op.add_column('entity', sa.Column('google_place_address', sa.Text(), nullable=True))
    op.add_column('entity', sa.Column('google_place_saved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entity', sa.Column('google_place_saved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('entity', sa.Column('place_provenance', sa.Enum('MANUAL', 'GOOGLE_PLACES', 'SEEDED', name='place_provenance', native_enum=False), server_default='MANUAL', nullable=False))
    op.create_index('ix_entity_muni_subtype', 'entity', ['municipality_id', 'subtype'], unique=False)
    op.create_unique_constraint('uq_entity_muni_place_id', 'entity', ['municipality_id', 'google_place_id'])
    op.create_foreign_key('fk_entity_google_place_saved_by_user', 'entity', 'app_user', ['google_place_saved_by_user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_check_constraint('ck_entity_expected_daily_kg', 'entity', 'expected_daily_kg IS NULL OR expected_daily_kg >= 0')
    op.create_check_constraint('ck_entity_google_place_id_present', 'entity', 'google_place_id IS NULL OR length(google_place_id) > 0')
    op.create_check_constraint('ck_entity_latitude_range', 'entity', 'latitude IS NULL OR (latitude >= -90 AND latitude <= 90)')
    op.create_check_constraint('ck_entity_longitude_range', 'entity', 'longitude IS NULL OR (longitude >= -180 AND longitude <= 180)')
    op.add_column('vehicle', sa.Column('last_speed_kmh', sa.Float(), nullable=True))
    op.add_column('vehicle', sa.Column('last_heading_degrees', sa.Float(), nullable=True))
    op.add_column('vehicle', sa.Column('telemetry_status', sa.Enum('UNKNOWN', 'MOVING', 'IDLE', 'OFFLINE', 'STALE', name='telemetry_status', native_enum=False), server_default='UNKNOWN', nullable=False))
    op.add_column('vehicle', sa.Column('telemetry_source', sa.Enum('NONE', 'SIMULATED', 'BROWSER_GPS', 'TRACKER_API', 'MANUAL', name='telemetry_source', native_enum=False), server_default='NONE', nullable=False))
    op.add_column('vehicle', sa.Column('tracker_device_id', sa.String(length=128), nullable=True))
    op.add_column('vehicle', sa.Column('telemetry_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_vehicle_muni_position_time', 'vehicle', ['municipality_id', 'last_position_at'], unique=False)
    op.create_check_constraint('ck_vehicle_last_heading_range', 'vehicle', 'last_heading_degrees IS NULL OR (last_heading_degrees >= 0 AND last_heading_degrees <= 360)')
    op.create_check_constraint('ck_vehicle_last_latitude_range', 'vehicle', 'last_latitude IS NULL OR (last_latitude >= -90 AND last_latitude <= 90)')
    op.create_check_constraint('ck_vehicle_last_longitude_range', 'vehicle', 'last_longitude IS NULL OR (last_longitude >= -180 AND last_longitude <= 180)')
    op.create_check_constraint('ck_vehicle_last_speed_nonneg', 'vehicle', 'last_speed_kmh IS NULL OR last_speed_kmh >= 0')
    op.add_column('waste_record', sa.Column('collection_status', sa.Enum('NOT_COLLECTED', 'COLLECTED', name='collection_status', native_enum=False), server_default='NOT_COLLECTED', nullable=False))
    op.add_column('waste_record', sa.Column('collected_on', sa.Date(), nullable=True))
    op.add_column('waste_record', sa.Column('measured_on', sa.Date(), nullable=True))
    op.add_column('waste_record', sa.Column('collection_status_set_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('waste_record', sa.Column('collection_status_set_by_user_id', sa.Integer(), nullable=True))
    op.add_column('waste_record', sa.Column('is_manual_entry', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_waste_record_muni_status_date', 'waste_record', ['municipality_id', 'collection_status', 'measured_on'], unique=False)
    op.create_foreign_key(None, 'waste_record', 'app_user', ['collection_status_set_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_waste_record_collection_semantics', 'waste_record', "(collection_status = 'COLLECTED' AND collected_on IS NOT NULL) OR (collection_status <> 'COLLECTED' AND collected_on IS NULL)")
    op.create_check_constraint('ck_waste_record_landfill', 'waste_record', 'landfill_kg IS NULL OR landfill_kg >= 0')
    op.create_check_constraint('ck_waste_record_recycled', 'waste_record', 'recycled_kg IS NULL OR recycled_kg >= 0')
    op.create_check_constraint('ck_waste_record_volume', 'waste_record', 'volume_liters IS NULL OR volume_liters >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_waste_record_volume', 'waste_record', type_='check')
    op.drop_constraint('ck_waste_record_recycled', 'waste_record', type_='check')
    op.drop_constraint('ck_waste_record_landfill', 'waste_record', type_='check')
    op.drop_constraint('ck_waste_record_collection_semantics', 'waste_record', type_='check')
    op.drop_constraint(None, 'waste_record', type_='foreignkey')
    op.drop_index('ix_waste_record_muni_status_date', table_name='waste_record')
    op.drop_column('waste_record', 'is_manual_entry')
    op.drop_column('waste_record', 'collection_status_set_by_user_id')
    op.drop_column('waste_record', 'collection_status_set_at')
    op.drop_column('waste_record', 'measured_on')
    op.drop_column('waste_record', 'collected_on')
    op.drop_column('waste_record', 'collection_status')
    op.drop_constraint('ck_vehicle_last_speed_nonneg', 'vehicle', type_='check')
    op.drop_constraint('ck_vehicle_last_longitude_range', 'vehicle', type_='check')
    op.drop_constraint('ck_vehicle_last_latitude_range', 'vehicle', type_='check')
    op.drop_constraint('ck_vehicle_last_heading_range', 'vehicle', type_='check')
    op.drop_index('ix_vehicle_muni_position_time', table_name='vehicle')
    op.drop_column('vehicle', 'telemetry_updated_at')
    op.drop_column('vehicle', 'tracker_device_id')
    op.drop_column('vehicle', 'telemetry_source')
    op.drop_column('vehicle', 'telemetry_status')
    op.drop_column('vehicle', 'last_heading_degrees')
    op.drop_column('vehicle', 'last_speed_kmh')
    op.drop_constraint('ck_entity_longitude_range', 'entity', type_='check')
    op.drop_constraint('ck_entity_latitude_range', 'entity', type_='check')
    op.drop_constraint('ck_entity_google_place_id_present', 'entity', type_='check')
    op.drop_constraint('ck_entity_expected_daily_kg', 'entity', type_='check')
    op.drop_constraint('fk_entity_google_place_saved_by_user', 'entity', type_='foreignkey')
    op.drop_constraint('uq_entity_muni_place_id', 'entity', type_='unique')
    op.drop_index('ix_entity_muni_subtype', table_name='entity')
    op.drop_column('entity', 'place_provenance')
    op.drop_column('entity', 'google_place_saved_by_user_id')
    op.drop_column('entity', 'google_place_saved_at')
    op.drop_column('entity', 'google_place_address')
    op.drop_column('entity', 'google_place_name')
    op.drop_column('entity', 'google_place_id')
    op.drop_column('entity', 'subtype')
    op.drop_constraint('ck_bin_longitude_range', 'bin', type_='check')
    op.drop_constraint('ck_bin_latitude_range', 'bin', type_='check')
    op.drop_constraint('ck_bin_capacity_liters_nonneg', 'bin', type_='check')
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_index('ix_app_user_muni_assigned_entity', table_name='app_user')
    op.drop_column('app_user', 'assigned_entity_at')
    op.drop_column('app_user', 'assigned_entity_id')
    op.drop_index('ix_vehicle_location_vehicle_time', table_name='vehicle_location')
    op.drop_index('ix_vehicle_location_time', table_name='vehicle_location')
    op.drop_index('ix_vehicle_location_muni_time', table_name='vehicle_location')
    op.drop_table('vehicle_location')
    # ### end Alembic commands ###
