"""create_zwaste_schema

Revision ID: a27f4314795e
Revises: 
Create Date: 2026-09-05 07:39:10.798901
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a27f4314795e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_municipality_code')
    )
    op.create_index('ix_municipality_active_name', 'municipality', ['is_active', 'name'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'MUNICIPAL_ADMIN', 'OPERATOR', 'DRIVER', 'ANALYST', 'VIEWER', name='user_role', native_enum=False), nullable=False),
    sa.Column('role_source_group', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_municipality_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_municipality_id'], ['municipality.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'subject', name='uq_app_user_provider_sub')
    )
    op.create_index('ix_app_user_email', 'app_user', ['email'], unique=False)
    op.create_index('ix_app_user_role', 'app_user', ['role'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('INSTITUTION', 'BUSINESS', 'HOSPITAL', 'HOUSEHOLD', 'PUBLIC_SPACE', name='entity_kind', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=True),
    sa.Column('area_name', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('occupancy', sa.Integer(), nullable=True),
    sa.Column('expected_daily_kg', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_future_architecture', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'code', name='uq_entity_muni_code')
    )
    op.create_index('ix_entity_muni_kind_active', 'entity', ['municipality_id', 'kind', 'is_active'], unique=False)
    op.create_index('ix_entity_name', 'entity', ['name'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('capacity_liters', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(length=48), nullable=True),
    sa.Column('odometer_km', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_ROUTE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='vehicle_status', native_enum=False), nullable=False),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('last_position_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_service_due_on', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'plate_number', name='uq_vehicle_muni_plate')
    )
    op.create_index('ix_vehicle_muni_status', 'vehicle', ['municipality_id', 'status'], unique=False)
    op.create_table('waste_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('color_hex', sa.String(length=9), nullable=False),
    sa.Column('is_hazardous', sa.Boolean(), nullable=False),
    sa.Column('is_recyclable', sa.Boolean(), nullable=False),
    sa.Column('density_kg_per_m3', sa.Float(), nullable=True),
    sa.Column('handling_instructions', sa.Text(), nullable=True),
    sa.Column('disposal_cost_per_kg', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'code', name='uq_waste_type_muni_code')
    )
    op.create_index('ix_waste_type_muni_active', 'waste_type', ['municipality_id', 'is_active'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.Enum('SUPER_ADMIN', 'MUNICIPAL_ADMIN', 'OPERATOR', 'DRIVER', 'ANALYST', 'VIEWER', name='user_role', native_enum=False), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DEACTIVATE', 'REACTIVATE', 'DELETE', 'LOGIN', 'ROLE_CHANGE', 'APPROVE', 'REJECT', 'EXPORT', 'SIMULATE', name='audit_action', native_enum=False), nullable=False),
    sa.Column('table_name', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity_ref', 'audit_log', ['table_name', 'record_id'], unique=False)
    op.create_index('ix_audit_muni_time', 'audit_log', ['municipality_id', 'created_at'], unique=False)
    op.create_index('ix_audit_user_time', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('bin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('waste_type_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('container_type', sa.String(length=80), nullable=True),
    sa.Column('capacity_liters', sa.Float(), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('fill_percent', sa.Float(), nullable=False),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OK', 'FILLING', 'NEAR_FULL', 'FULL', 'OVERFLOW', 'OFFLINE', 'MAINTENANCE', name='bin_status', native_enum=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area_name', sa.String(length=120), nullable=True),
    sa.Column('installed_on', sa.Date(), nullable=True),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_emptied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_threshold_percent', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fill_percent >= 0 AND fill_percent <= 100', name='ck_bin_fill_range'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_type_id'], ['waste_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'code', name='uq_bin_muni_code')
    )
    op.create_index('ix_bin_entity', 'bin', ['entity_id'], unique=False)
    op.create_index('ix_bin_muni_status', 'bin', ['municipality_id', 'status'], unique=False)
    op.create_table('business_profile',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('operating_hours', sa.String(length=120), nullable=True),
    sa.Column('commercial_waste_licence', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('employee_code', sa.String(length=48), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('licence_number', sa.String(length=64), nullable=True),
    sa.Column('licence_class', sa.String(length=32), nullable=True),
    sa.Column('licence_expires_on', sa.Date(), nullable=True),
    sa.Column('shift', sa.String(length=48), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'employee_code', name='uq_driver_muni_code')
    )
    op.create_index('ix_driver_muni_active', 'driver', ['municipality_id', 'is_active'], unique=False)
    op.create_table('hospital_profile',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('facility_level', sa.String(length=120), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('has_incinerator', sa.Boolean(), nullable=False),
    sa.Column('hazardous_handling_certified', sa.Boolean(), nullable=False),
    sa.Column('biohazard_pickup_frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('household_profile',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('dwelling_type', sa.String(length=120), nullable=True),
    sa.Column('resident_count', sa.Integer(), nullable=True),
    sa.Column('household_head', sa.String(length=160), nullable=True),
    sa.Column('subscription_plan', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('institution_profile',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('institution_type', sa.String(length=120), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('staff_count', sa.Integer(), nullable=True),
    sa.Column('campus_count', sa.Integer(), nullable=False),
    sa.Column('recycling_program', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('municipality_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'MUNICIPAL_ADMIN', 'OPERATOR', 'DRIVER', 'ANALYST', 'VIEWER', name='user_role', native_enum=False), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'municipality_id', name='uq_membership_user_muni')
    )
    op.create_index('ix_membership_municipality_role', 'municipality_membership', ['municipality_id', 'role'], unique=False)
    op.create_index(op.f('ix_municipality_membership_user_id'), 'municipality_membership', ['user_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'ENTITY', 'AREA', 'WASTE_TYPE', 'PERFORMANCE', 'CUSTOM', name='report_kind', native_enum=False), nullable=False),
    sa.Column('export_format', sa.Enum('CSV', 'PDF', name='report_format', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'GENERATING', 'READY', 'FAILED', name='report_status', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('waste_type_id', sa.Integer(), nullable=True),
    sa.Column('area_name', sa.String(length=120), nullable=True),
    sa.Column('filters_summary', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_type_id'], ['waste_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_muni_kind_time', 'report', ['municipality_id', 'kind', 'created_at'], unique=False)
    op.create_table('driver_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignment_driver', 'driver_assignment', ['driver_id'], unique=False)
    op.create_index('ix_assignment_muni_start', 'driver_assignment', ['municipality_id', 'starts_at'], unique=False)
    op.create_index('ix_assignment_vehicle', 'driver_assignment', ['vehicle_id'], unique=False)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('OVERFLOW_FORECAST', 'VOLUME_FORECAST', 'ANOMALY_SCORE', 'COLLECTION_RECOMMENDATION', 'ROUTE_RECOMMENDATION', 'VEHICLE_RECOMMENDATION', name='prediction_kind', native_enum=False), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('horizon_hours', sa.Integer(), nullable=True),
    sa.Column('predicted_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=120), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approval_status', native_enum=False), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_approval', 'prediction', ['approval_status'], unique=False)
    op.create_index('ix_prediction_bin', 'prediction', ['bin_id'], unique=False)
    op.create_index('ix_prediction_muni_kind_time', 'prediction', ['municipality_id', 'kind', 'created_at'], unique=False)
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('device_serial', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('firmware_version', sa.String(length=48), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAULTY', 'LOW_BATTERY', 'CALIBRATING', name='sensor_status', native_enum=False), nullable=False),
    sa.Column('battery_percent', sa.Float(), nullable=True),
    sa.Column('signal_strength_dbm', sa.Float(), nullable=True),
    sa.Column('reporting_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('installed_on', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_serial', name='uq_sensor_device_serial')
    )
    op.create_index('ix_sensor_bin', 'sensor', ['bin_id'], unique=False)
    op.create_index('ix_sensor_muni_status', 'sensor', ['municipality_id', 'status'], unique=False)
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='route_status', native_enum=False), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_distance_km', sa.Float(), nullable=True),
    sa.Column('actual_distance_km', sa.Float(), nullable=True),
    sa.Column('planned_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_collected_kg', sa.Float(), nullable=True),
    sa.Column('generated_from_prediction_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_from_prediction_id'], ['prediction.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_route_generated_from_prediction', 'route', ['generated_from_prediction_id'], unique=False)
    op.create_index('ix_route_muni_status_date', 'route', ['municipality_id', 'status', 'scheduled_for'], unique=False)
    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fill_percent', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('distance_cm', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('gas_ppm', sa.Float(), nullable=True),
    sa.Column('battery_percent', sa.Float(), nullable=True),
    sa.Column('lid_open', sa.Boolean(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reading_bin_time', 'sensor_reading', ['bin_id', 'recorded_at'], unique=False)
    op.create_index('ix_reading_muni_time', 'sensor_reading', ['municipality_id', 'recorded_at'], unique=False)
    op.create_index('ix_reading_sensor_time', 'sensor_reading', ['sensor_id', 'recorded_at'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('BIN_FULL', 'OVERFLOW_FORECAST', 'SENSOR_FAULT', 'SENSOR_OFFLINE', 'ANOMALY', 'ROUTE_DELAY', 'MISSED_COLLECTION', 'HAZARDOUS_WASTE', name='alert_kind', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alert_status', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('sensor_reading_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bin_id'], ['bin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_reading_id'], ['sensor_reading.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_bin_time', 'alert', ['bin_id', 'created_at'], unique=False)
    op.create_index('ix_alert_muni_status_sev', 'alert', ['municipality_id', 'status', 'severity'], unique=False)
    op.create_table('route_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'EN_ROUTE', 'COLLECTED', 'SKIPPED', 'FAILED', name='stop_status', native_enum=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_kg', sa.Float(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence', name='uq_route_stop_sequence')
    )
    op.create_index('ix_route_stop_bin', 'route_stop', ['bin_id'], unique=False)
    op.create_index('ix_route_stop_status', 'route_stop', ['route_id', 'status'], unique=False)
    op.create_table('waste_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('waste_type_id', sa.Integer(), nullable=True),
    sa.Column('route_stop_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('volume_liters', sa.Float(), nullable=True),
    sa.Column('recycled_kg', sa.Float(), nullable=True),
    sa.Column('landfill_kg', sa.Float(), nullable=True),
    sa.Column('disposal_site', sa.String(length=160), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('SIMULATED', 'MANUAL', 'SENSOR', 'GATEZ_DEVICE', 'API', 'IMPORT', 'DERIVED', name='data_source', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_kg >= 0', name='ck_waste_record_qty'),
    sa.ForeignKeyConstraint(['bin_id'], ['bin.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stop.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waste_type_id'], ['waste_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waste_record_entity_time', 'waste_record', ['entity_id', 'collected_at'], unique=False)
    op.create_index('ix_waste_record_muni_time', 'waste_record', ['municipality_id', 'collected_at'], unique=False)
    op.create_index('ix_waste_record_type', 'waste_record', ['waste_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waste_record_type', table_name='waste_record')
    op.drop_index('ix_waste_record_muni_time', table_name='waste_record')
    op.drop_index('ix_waste_record_entity_time', table_name='waste_record')
    op.drop_table('waste_record')
    op.drop_index('ix_route_stop_status', table_name='route_stop')
    op.drop_index('ix_route_stop_bin', table_name='route_stop')
    op.drop_table('route_stop')
    op.drop_index('ix_alert_muni_status_sev', table_name='alert')
    op.drop_index('ix_alert_bin_time', table_name='alert')
    op.drop_table('alert')
    op.drop_index('ix_reading_sensor_time', table_name='sensor_reading')
    op.drop_index('ix_reading_muni_time', table_name='sensor_reading')
    op.drop_index('ix_reading_bin_time', table_name='sensor_reading')
    op.drop_table('sensor_reading')
    op.drop_index('ix_route_muni_status_date', table_name='route')
    op.drop_index('ix_route_generated_from_prediction', table_name='route')
    op.drop_table('route')
    op.drop_index('ix_sensor_muni_status', table_name='sensor')
    op.drop_index('ix_sensor_bin', table_name='sensor')
    op.drop_table('sensor')
    op.drop_index('ix_prediction_muni_kind_time', table_name='prediction')
    op.drop_index('ix_prediction_bin', table_name='prediction')
    op.drop_index('ix_prediction_approval', table_name='prediction')
    op.drop_table('prediction')
    op.drop_index('ix_assignment_vehicle', table_name='driver_assignment')
    op.drop_index('ix_assignment_muni_start', table_name='driver_assignment')
    op.drop_index('ix_assignment_driver', table_name='driver_assignment')
    op.drop_table('driver_assignment')
    op.drop_index('ix_report_muni_kind_time', table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_municipality_membership_user_id'), table_name='municipality_membership')
    op.drop_index('ix_membership_municipality_role', table_name='municipality_membership')
    op.drop_table('municipality_membership')
    op.drop_table('institution_profile')
    op.drop_table('household_profile')
    op.drop_table('hospital_profile')
    op.drop_index('ix_driver_muni_active', table_name='driver')
    op.drop_table('driver')
    op.drop_table('business_profile')
    op.drop_index('ix_bin_muni_status', table_name='bin')
    op.drop_index('ix_bin_entity', table_name='bin')
    op.drop_table('bin')
    op.drop_index('ix_audit_user_time', table_name='audit_log')
    op.drop_index('ix_audit_muni_time', table_name='audit_log')
    op.drop_index('ix_audit_entity_ref', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_waste_type_muni_active', table_name='waste_type')
    op.drop_table('waste_type')
    op.drop_index('ix_vehicle_muni_status', table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index('ix_entity_name', table_name='entity')
    op.drop_index('ix_entity_muni_kind_active', table_name='entity')
    op.drop_table('entity')
    op.drop_index('ix_app_user_role', table_name='app_user')
    op.drop_index('ix_app_user_email', table_name='app_user')
    op.drop_table('app_user')
    op.drop_index('ix_municipality_active_name', table_name='municipality')
    op.drop_table('municipality')
    # ### end Alembic commands ###
